"""initial migration

Revision ID: 3313e8b30d18
Revises: 75f6e76f2904
Create Date: 2025-08-22 11:06:54.780341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3313e8b30d18'
down_revision: Union[str, Sequence[str], None] = '75f6e76f2904'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reddit_schedules', sa.Column('start_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('reddit_schedules', sa.Column('end_date', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reddit_schedules', 'end_date')
    op.drop_column('reddit_schedules', 'start_date')
    # ### end Alembic commands ###
