"""add schedule and niche support

Revision ID: 75f6e76f2904
Revises: 15c94c4e6f97
Create Date: 2025-08-22 03:02:55.003374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75f6e76f2904'
down_revision: Union[str, Sequence[str], None] = '15c94c4e6f97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reddit_accounts', sa.Column('niche', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reddit_accounts', 'niche')
    # ### end Alembic commands ###
