"""excuted field

Revision ID: ff3c4006263c
Revises: 196beb186bd7
Create Date: 2025-08-23 00:07:50.068058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff3c4006263c'
down_revision: Union[str, Sequence[str], None] = '196beb186bd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reddit_schedules', sa.Column('excuted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reddit_schedules', 'excuted')
    # ### end Alembic commands ###
